# .readthedocs.yaml
version: 2

build:
  os: ubuntu-lts-latest # ubuntu-22.04 is the current LTS alias
  tools:
    python: "3.10"

formats:
 - htmlzip
 - pdf

sphinx:
  configuration: docs/conf.py

# Define python requirements
python:
  install:
    - requirements: docs/requirements.txt
    # Alternatively, list packages directly:
    # - method: pip
    #   packages:
    #     - myst-parser
    #     - pymdown-extensions