version: 2
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.10"
formats:
 - htmlzip
 - pdf
sphinx:
  configuration: docs/conf.py
markdown:
  extensions:
    - admonitions
    - codehilite(guess_lang=False)
    - footnotes
    - pymdownx.arithmatex
    - pymdownx.betterem(smart_enable=all)
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist
    - pymdownx.tilde