version: 2

build:
  os: ubuntu-latest
  tools:
    python: "3.10"

formats:
 - htmlzip
 - pdf

markdown:
  version: ">= 3.0"
  extensions:
    - admonitions
    - codehilite(guess_lang=False)
    - footnotes
    - pymdownx.arithmatex
    - pymdownx.betterem(smart_enable=all)
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_alt
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist
    - pymdownx.tilde